language: ruby
cache: bundler
branches:
  only:
  -  master
addons:
  ssh_known_hosts: git.wpengine.com
script:
- cd wp-content/themes/missile-defense
- compass compile
before_install:
- openssl aes-256-cbc -K $encrypted_243a311f58f2_key -iv $encrypted_243a311f58f2_iv
  -in missile_rsa.enc -out /tmp/missile_rsa -d
- gem install compass
before_deploy:
- cd $TRAVIS_BUILD_DIR
deploy:
- provider: script
  skip_cleanup: true
  script: chmod +x deploy.sh && sh deploy.sh
  on:
    branch: master