language: node_js
node_js:
  - lts/*
branches:
  only:
    - main
    - development
addons:
  ssh_known_hosts: git.wpengine.com
script:
  - pushd wp-content/themes/missilethreat; npm run build; popd
before_install:
  - openssl aes-256-cbc -K $encrypted_243a311f58f2_key -iv $encrypted_243a311f58f2_iv -in missile_rsa.enc -out /tmp/missile_rsa -d
install:
  - pushd wp-content/themes/missilethreat; npm install; popd
before_deploy:
  - cd $TRAVIS_BUILD_DIR
deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x deploy-development.sh && sh deploy-development.sh
    on:
      branch: development
  - provider: script
    skip_cleanup: true
    script: chmod +x deploy-staging.sh && sh deploy-staging.sh
    on:
      branch: main
